// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

type Attachment struct {
	ID          string
	ChatID      string
	MessageID   string
	Filename    string
	Kind        string
	Mime        string
	Size        int64
	Data        []byte
	Description string
	CreatedAt   int64
}

type Chat struct {
	ID             string
	Title          string
	TitleGenerated int64
	Model          string
	ParamsJson     string
	ToolsJson      string
	CreatedAt      int64
	UpdatedAt      int64
}

type Config struct {
	Key       string
	Value     string
	UpdatedAt int64
}

type Message struct {
	Seq              int64
	ID               string
	ChatID           string
	Role             string
	Status           string
	Content          string
	Reasoning        string
	Error            string
	ToolCallID       string
	Name             string
	Model            string
	PromptTokens     int64
	CompletionTokens int64
	DurationMs       int64
	CreatedAt        int64
	UpdatedAt        int64
}

type Model struct {
	ModelID          string
	InputModality    string
	OutputModality   string
	ContextLength    int64
	ReasoningEfforts string
	ReasoningDefault string
	UpdatedAt        int64
}

type ToolCall struct {
	ID             string
	MessageID      string
	ProviderCallID string
	Name           string
	Arguments      string
	Position       int64
}
