// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package query

import (
	"context"
)

const chatExists = `-- name: ChatExists :one
SELECT COUNT(*) FROM chats WHERE id = ?
`

func (q *Queries) ChatExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, chatExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const chatTokenTotals = `-- name: ChatTokenTotals :one
SELECT
  -- CAST gives sqlc a declared INTEGER type for the aggregate expressions.
  CAST(COALESCE(SUM(prompt_tokens), 0) AS INTEGER) AS prompt_total,
  CAST(COALESCE(SUM(completion_tokens), 0) AS INTEGER) AS completion_total
FROM messages
WHERE chat_id = ? AND role = 'assistant'
`

type ChatTokenTotalsRow struct {
	PromptTotal     int64
	CompletionTotal int64
}

func (q *Queries) ChatTokenTotals(ctx context.Context, chatID string) (ChatTokenTotalsRow, error) {
	row := q.db.QueryRowContext(ctx, chatTokenTotals, chatID)
	var i ChatTokenTotalsRow
	err := row.Scan(&i.PromptTotal, &i.CompletionTotal)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :exec

INSERT INTO attachments (id, chat_id, message_id, filename, kind, mime, size, data, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	ID        string
	ChatID    string
	MessageID string
	Filename  string
	Kind      string
	Mime      string
	Size      int64
	Data      []byte
	CreatedAt int64
}

// ---- attachments ----
func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.ChatID,
		arg.MessageID,
		arg.Filename,
		arg.Kind,
		arg.Mime,
		arg.Size,
		arg.Data,
		arg.CreatedAt,
	)
	return err
}

const createChat = `-- name: CreateChat :exec


INSERT INTO chats (id, title, model, params_json, tools_json, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateChatParams struct {
	ID         string
	Title      string
	Model      string
	ParamsJson string
	ToolsJson  string
	CreatedAt  int64
	UpdatedAt  int64
}

// Chattoneko business queries (sqlc input). Cursor/optional values are
// expressed as empty strings / sentinel values rather than NULL.
// ---- chats ----
func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.ExecContext(ctx, createChat,
		arg.ID,
		arg.Title,
		arg.Model,
		arg.ParamsJson,
		arg.ToolsJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec

INSERT INTO messages (id, chat_id, role, status, content, reasoning, error, tool_call_id, name, model, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID         string
	ChatID     string
	Role       string
	Status     string
	Content    string
	Reasoning  string
	Error      string
	ToolCallID string
	Name       string
	Model      string
	CreatedAt  int64
	UpdatedAt  int64
}

// ---- messages ----
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ChatID,
		arg.Role,
		arg.Status,
		arg.Content,
		arg.Reasoning,
		arg.Error,
		arg.ToolCallID,
		arg.Name,
		arg.Model,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createToolCall = `-- name: CreateToolCall :exec

INSERT INTO tool_calls (id, message_id, provider_call_id, name, arguments, position)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateToolCallParams struct {
	ID             string
	MessageID      string
	ProviderCallID string
	Name           string
	Arguments      string
	Position       int64
}

// ---- tool_calls ----
func (q *Queries) CreateToolCall(ctx context.Context, arg CreateToolCallParams) error {
	_, err := q.db.ExecContext(ctx, createToolCall,
		arg.ID,
		arg.MessageID,
		arg.ProviderCallID,
		arg.Name,
		arg.Arguments,
		arg.Position,
	)
	return err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
DELETE FROM attachments WHERE id = ? AND message_id = ?
`

type DeleteAttachmentParams struct {
	ID        string
	MessageID string
}

func (q *Queries) DeleteAttachment(ctx context.Context, arg DeleteAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, deleteAttachment, arg.ID, arg.MessageID)
	return err
}

const deleteChat = `-- name: DeleteChat :exec
DELETE FROM chats WHERE id = ?
`

func (q *Queries) DeleteChat(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteChat, id)
	return err
}

const deleteDanglingAttachments = `-- name: DeleteDanglingAttachments :exec
DELETE FROM attachments
WHERE attachments.chat_id = ? AND attachments.message_id != ''
  AND attachments.message_id NOT IN
    (SELECT m.id FROM messages m WHERE m.chat_id = attachments.chat_id)
`

// Attachments whose message was truncated away (regenerate / edit-resend).
// attachments.message_id has no FK (uploads legitimately start unlinked), so
// deleting messages leaves linked rows dangling; this cleans them up.
func (q *Queries) DeleteDanglingAttachments(ctx context.Context, chatID string) error {
	_, err := q.db.ExecContext(ctx, deleteDanglingAttachments, chatID)
	return err
}

const deleteMessagesAfterSeq = `-- name: DeleteMessagesAfterSeq :exec
DELETE FROM messages WHERE chat_id = ? AND seq > ?
`

type DeleteMessagesAfterSeqParams struct {
	ChatID string
	Seq    int64
}

func (q *Queries) DeleteMessagesAfterSeq(ctx context.Context, arg DeleteMessagesAfterSeqParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesAfterSeq, arg.ChatID, arg.Seq)
	return err
}

const deleteMessagesFromSeq = `-- name: DeleteMessagesFromSeq :exec
DELETE FROM messages WHERE chat_id = ? AND seq >= ?
`

type DeleteMessagesFromSeqParams struct {
	ChatID string
	Seq    int64
}

func (q *Queries) DeleteMessagesFromSeq(ctx context.Context, arg DeleteMessagesFromSeqParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesFromSeq, arg.ChatID, arg.Seq)
	return err
}

const deleteOrphanAttachmentsOlderThan = `-- name: DeleteOrphanAttachmentsOlderThan :exec
DELETE FROM attachments WHERE message_id = '' AND created_at < ?
`

func (q *Queries) DeleteOrphanAttachmentsOlderThan(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanAttachmentsOlderThan, createdAt)
	return err
}

const distinctToolNamesInChat = `-- name: DistinctToolNamesInChat :many
SELECT DISTINCT tc.name
FROM tool_calls tc
JOIN messages m ON m.id = tc.message_id
WHERE m.chat_id = ?
`

func (q *Queries) DistinctToolNamesInChat(ctx context.Context, chatID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctToolNamesInChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const firstUserMessage = `-- name: FirstUserMessage :one
SELECT seq, id, chat_id, role, status, content, reasoning, error, tool_call_id, name, model, prompt_tokens, completion_tokens, duration_ms, created_at, updated_at FROM messages
WHERE chat_id = ? AND role = 'user'
ORDER BY seq ASC
LIMIT 1
`

// First user message of a chat (the title task's input).
func (q *Queries) FirstUserMessage(ctx context.Context, chatID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, firstUserMessage, chatID)
	var i Message
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Reasoning,
		&i.Error,
		&i.ToolCallID,
		&i.Name,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, chat_id, message_id, filename, kind, mime, size, data, description, created_at FROM attachments WHERE id = ?
`

func (q *Queries) GetAttachment(ctx context.Context, id string) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.MessageID,
		&i.Filename,
		&i.Kind,
		&i.Mime,
		&i.Size,
		&i.Data,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getChat = `-- name: GetChat :one
SELECT id, title, title_generated, model, params_json, tools_json, created_at, updated_at FROM chats WHERE id = ?
`

func (q *Queries) GetChat(ctx context.Context, id string) (Chat, error) {
	row := q.db.QueryRowContext(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleGenerated,
		&i.Model,
		&i.ParamsJson,
		&i.ToolsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT seq, id, chat_id, role, status, content, reasoning, error, tool_call_id, name, model, prompt_tokens, completion_tokens, duration_ms, created_at, updated_at FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Reasoning,
		&i.Error,
		&i.ToolCallID,
		&i.Name,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lastAssistantMessage = `-- name: LastAssistantMessage :one
SELECT seq, id, chat_id, role, status, content, reasoning, error, tool_call_id, name, model, prompt_tokens, completion_tokens, duration_ms, created_at, updated_at FROM messages
WHERE chat_id = ? AND role = 'assistant'
ORDER BY seq DESC
LIMIT 1
`

func (q *Queries) LastAssistantMessage(ctx context.Context, chatID string) (Message, error) {
	row := q.db.QueryRowContext(ctx, lastAssistantMessage, chatID)
	var i Message
	err := row.Scan(
		&i.Seq,
		&i.ID,
		&i.ChatID,
		&i.Role,
		&i.Status,
		&i.Content,
		&i.Reasoning,
		&i.Error,
		&i.ToolCallID,
		&i.Name,
		&i.Model,
		&i.PromptTokens,
		&i.CompletionTokens,
		&i.DurationMs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkAttachmentToMessage = `-- name: LinkAttachmentToMessage :exec
UPDATE attachments SET message_id = ? WHERE id = ? AND chat_id = ?
`

type LinkAttachmentToMessageParams struct {
	MessageID string
	ID        string
	ChatID    string
}

func (q *Queries) LinkAttachmentToMessage(ctx context.Context, arg LinkAttachmentToMessageParams) error {
	_, err := q.db.ExecContext(ctx, linkAttachmentToMessage, arg.MessageID, arg.ID, arg.ChatID)
	return err
}

const listAttachmentMetasForChat = `-- name: ListAttachmentMetasForChat :many
SELECT id, chat_id, message_id, filename, kind, mime, size, created_at,
       CAST((description != '') AS BOOLEAN) AS has_description
FROM attachments WHERE chat_id = ? ORDER BY created_at ASC
`

type ListAttachmentMetasForChatRow struct {
	ID             string
	ChatID         string
	MessageID      string
	Filename       string
	Kind           string
	Mime           string
	Size           int64
	CreatedAt      int64
	HasDescription bool
}

// Attachment metas for a whole chat (no blob data) - used to attach metas
// to messages in one query instead of one query per message.
func (q *Queries) ListAttachmentMetasForChat(ctx context.Context, chatID string) ([]ListAttachmentMetasForChatRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentMetasForChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentMetasForChatRow
	for rows.Next() {
		var i ListAttachmentMetasForChatRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.MessageID,
			&i.Filename,
			&i.Kind,
			&i.Mime,
			&i.Size,
			&i.CreatedAt,
			&i.HasDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByMessage = `-- name: ListAttachmentsByMessage :many
SELECT id, chat_id, message_id, filename, kind, mime, size, data, description, created_at FROM attachments WHERE message_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByMessage(ctx context.Context, messageID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.MessageID,
			&i.Filename,
			&i.Kind,
			&i.Mime,
			&i.Size,
			&i.Data,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChats = `-- name: ListChats :many
SELECT id, title, title_generated, model, params_json, tools_json, created_at, updated_at FROM chats
ORDER BY updated_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListChats(ctx context.Context, limit int64) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChats, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleGenerated,
			&i.Model,
			&i.ParamsJson,
			&i.ToolsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsBefore = `-- name: ListChatsBefore :many
SELECT id, title, title_generated, model, params_json, tools_json, created_at, updated_at FROM chats
WHERE (updated_at < ?)
   OR (updated_at = ? AND id < ?)
ORDER BY updated_at DESC, id DESC
LIMIT ?
`

type ListChatsBeforeParams struct {
	UpdatedAt   int64
	UpdatedAt_2 int64
	ID          string
	Limit       int64
}

func (q *Queries) ListChatsBefore(ctx context.Context, arg ListChatsBeforeParams) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listChatsBefore,
		arg.UpdatedAt,
		arg.UpdatedAt_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleGenerated,
			&i.Model,
			&i.ParamsJson,
			&i.ToolsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatsNeedingTitle = `-- name: ListChatsNeedingTitle :many
SELECT id FROM chats WHERE title_generated = 0 ORDER BY created_at ASC LIMIT ?
`

// Background title task: chats whose title is not final yet. Manual renames
// flip the flag, and the task itself sets it when done.
func (q *Queries) ListChatsNeedingTitle(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listChatsNeedingTitle, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDanglingToolCalls = `-- name: ListDanglingToolCalls :many
SELECT tc.id, tc.message_id, tc.provider_call_id, tc.name, tc.arguments, tc.position
FROM tool_calls tc
JOIN messages m ON m.id = tc.message_id
WHERE tc.message_id = ?
  AND NOT EXISTS (
    SELECT 1 FROM messages r
    WHERE r.chat_id = m.chat_id
      AND r.role = 'tool'
      AND r.tool_call_id = tc.provider_call_id
  )
`

func (q *Queries) ListDanglingToolCalls(ctx context.Context, messageID string) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listDanglingToolCalls, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCall
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProviderCallID,
			&i.Name,
			&i.Arguments,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmptyChatsOlderThan = `-- name: ListEmptyChatsOlderThan :many
SELECT c.id, c.title, c.title_generated, c.model, c.params_json, c.tools_json, c.created_at, c.updated_at FROM chats c
WHERE c.created_at < ?
  AND NOT EXISTS (SELECT 1 FROM messages m WHERE m.chat_id = c.id)
`

func (q *Queries) ListEmptyChatsOlderThan(ctx context.Context, createdAt int64) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, listEmptyChatsOlderThan, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleGenerated,
			&i.Model,
			&i.ParamsJson,
			&i.ToolsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeneratingMessages = `-- name: ListGeneratingMessages :many
SELECT seq, id, chat_id, role, status, content, reasoning, error, tool_call_id, name, model, prompt_tokens, completion_tokens, duration_ms, created_at, updated_at FROM messages WHERE status = 'generating'
`

func (q *Queries) ListGeneratingMessages(ctx context.Context) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listGeneratingMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.Reasoning,
			&i.Error,
			&i.ToolCallID,
			&i.Name,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChat = `-- name: ListMessagesByChat :many
SELECT seq, id, chat_id, role, status, content, reasoning, error, tool_call_id, name, model, prompt_tokens, completion_tokens, duration_ms, created_at, updated_at FROM messages WHERE chat_id = ? ORDER BY seq ASC
`

func (q *Queries) ListMessagesByChat(ctx context.Context, chatID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.Seq,
			&i.ID,
			&i.ChatID,
			&i.Role,
			&i.Status,
			&i.Content,
			&i.Reasoning,
			&i.Error,
			&i.ToolCallID,
			&i.Name,
			&i.Model,
			&i.PromptTokens,
			&i.CompletionTokens,
			&i.DurationMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsByMessage = `-- name: ListToolCallsByMessage :many
SELECT id, message_id, provider_call_id, name, arguments, position FROM tool_calls WHERE message_id = ? ORDER BY position ASC
`

func (q *Queries) ListToolCallsByMessage(ctx context.Context, messageID string) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listToolCallsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCall
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProviderCallID,
			&i.Name,
			&i.Arguments,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCallsForChat = `-- name: ListToolCallsForChat :many
SELECT tc.id, tc.message_id, tc.provider_call_id, tc.name, tc.arguments, tc.position FROM tool_calls tc
JOIN messages m ON m.id = tc.message_id
WHERE m.chat_id = ?
ORDER BY tc.position ASC
`

func (q *Queries) ListToolCallsForChat(ctx context.Context, chatID string) ([]ToolCall, error) {
	rows, err := q.db.QueryContext(ctx, listToolCallsForChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCall
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProviderCallID,
			&i.Name,
			&i.Arguments,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTitleGenerated = `-- name: MarkTitleGenerated :exec
UPDATE chats SET title_generated = 1 WHERE id = ?
`

// Bookkeeping-only: title stays as-is ("New Chat"), just stop retrying.
// Does NOT touch updated_at (nothing user-visible changed).
func (q *Queries) MarkTitleGenerated(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markTitleGenerated, id)
	return err
}

const searchChats = `-- name: SearchChats :many
SELECT c.id, c.title, c.title_generated, c.model, c.params_json, c.tools_json, c.created_at, c.updated_at FROM chats c
WHERE c.id IN (SELECT id FROM chats ORDER BY updated_at DESC, id DESC LIMIT ?)
  AND (
    instr(lower(c.title), lower(?)) > 0
    OR EXISTS (
      SELECT 1 FROM messages m
      WHERE m.chat_id = c.id
        AND instr(lower(m.content), lower(?)) > 0
    )
  )
ORDER BY c.updated_at DESC, c.id DESC
LIMIT ?
`

type SearchChatsParams struct {
	Limit   int64
	LOWER   string
	LOWER_2 string
	Limit_2 int64
}

// Title OR message-content search (#4): matches chats whose title contains
// the query, and chats with any message whose content contains it (so
// untitled chats and content-only matches are findable). Scans only the
// most recent chats (scan window) so the full-table instr() scan stays
// bounded; FTS5 would be the proper fix if search grows in importance.
func (q *Queries) SearchChats(ctx context.Context, arg SearchChatsParams) ([]Chat, error) {
	rows, err := q.db.QueryContext(ctx, searchChats,
		arg.Limit,
		arg.LOWER,
		arg.LOWER_2,
		arg.Limit_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleGenerated,
			&i.Model,
			&i.ParamsJson,
			&i.ToolsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAttachmentDescription = `-- name: SetAttachmentDescription :exec
UPDATE attachments SET description = ? WHERE id = ?
`

type SetAttachmentDescriptionParams struct {
	Description string
	ID          string
}

func (q *Queries) SetAttachmentDescription(ctx context.Context, arg SetAttachmentDescriptionParams) error {
	_, err := q.db.ExecContext(ctx, setAttachmentDescription, arg.Description, arg.ID)
	return err
}

const setGeneratedTitle = `-- name: SetGeneratedTitle :execrows
UPDATE chats SET title = ?, title_generated = 1, updated_at = ? WHERE id = ? AND title_generated = 0
`

type SetGeneratedTitleParams struct {
	Title     string
	UpdatedAt int64
	ID        string
}

// Conditional title write for the background task: the title_generated = 0
// guard makes a concurrent manual rename win (rows affected = 0 => skip the
// SSE broadcast; the user's title stays).
func (q *Queries) SetGeneratedTitle(ctx context.Context, arg SetGeneratedTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setGeneratedTitle, arg.Title, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchChat = `-- name: TouchChat :exec
UPDATE chats SET updated_at = ? WHERE id = ?
`

type TouchChatParams struct {
	UpdatedAt int64
	ID        string
}

func (q *Queries) TouchChat(ctx context.Context, arg TouchChatParams) error {
	_, err := q.db.ExecContext(ctx, touchChat, arg.UpdatedAt, arg.ID)
	return err
}

const updateChatSettings = `-- name: UpdateChatSettings :exec
UPDATE chats SET model = ?, params_json = ?, tools_json = ?, updated_at = ? WHERE id = ?
`

type UpdateChatSettingsParams struct {
	Model      string
	ParamsJson string
	ToolsJson  string
	UpdatedAt  int64
	ID         string
}

func (q *Queries) UpdateChatSettings(ctx context.Context, arg UpdateChatSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateChatSettings,
		arg.Model,
		arg.ParamsJson,
		arg.ToolsJson,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateChatTitle = `-- name: UpdateChatTitle :exec
UPDATE chats SET title = ?, title_generated = 1, updated_at = ? WHERE id = ?
`

type UpdateChatTitleParams struct {
	Title     string
	UpdatedAt int64
	ID        string
}

// Manual rename: also flips title_generated so the background title task
// never overwrites a user-chosen title (user takes ownership of the title).
func (q *Queries) UpdateChatTitle(ctx context.Context, arg UpdateChatTitleParams) error {
	_, err := q.db.ExecContext(ctx, updateChatTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE messages SET content = ?, reasoning = ?, updated_at = ? WHERE id = ?
`

type UpdateMessageContentParams struct {
	Content   string
	Reasoning string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageContent,
		arg.Content,
		arg.Reasoning,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE messages SET status = ?, error = ?, content = ?, reasoning = ?, updated_at = ? WHERE id = ?
`

type UpdateMessageStatusParams struct {
	Status    string
	Error     string
	Content   string
	Reasoning string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageStatus,
		arg.Status,
		arg.Error,
		arg.Content,
		arg.Reasoning,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateMessageUsage = `-- name: UpdateMessageUsage :exec
UPDATE messages SET prompt_tokens = ?, completion_tokens = ?, duration_ms = ?, updated_at = ? WHERE id = ?
`

type UpdateMessageUsageParams struct {
	PromptTokens     int64
	CompletionTokens int64
	DurationMs       int64
	UpdatedAt        int64
	ID               string
}

func (q *Queries) UpdateMessageUsage(ctx context.Context, arg UpdateMessageUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageUsage,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.DurationMs,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateUserMessageContent = `-- name: UpdateUserMessageContent :exec
UPDATE messages SET content = ?, updated_at = ? WHERE id = ? AND role = 'user'
`

type UpdateUserMessageContentParams struct {
	Content   string
	UpdatedAt int64
	ID        string
}

func (q *Queries) UpdateUserMessageContent(ctx context.Context, arg UpdateUserMessageContentParams) error {
	_, err := q.db.ExecContext(ctx, updateUserMessageContent, arg.Content, arg.UpdatedAt, arg.ID)
	return err
}
